[firebase]
  apiKey: "AIzaSyBKtn3M3gj_OBiP_fSg63omjhAO6t5QmS8"
  authDomain: "fir-chess-ff085.firebaseapp.com"
  projectId: "fir-chess-ff085"
  storageBucket: "fir-chess-ff085.firebasestorage.app"
  messagingSenderId: "495432935367"
  appId: "1:495432935367:web:13ab4012be185b9d69dbe2"
  measurementId: "G-FCHFP07YQ4"
